%% Import Matrices

load matlab_matrices.mat

%% Compute vectors to plot

% 2017 summer
[no_alg_3d_summer_2017_w_ind, bg_alg_3d_summer_2017_w_ind, ...
    gr_alg_3d_summer_2017_w_ind] = data_vectors(mat_summer_2017_norm, ...
    mat_summer_2017_w_ind_3d);
[no_alg_3d_summer_2017_no_ind, bg_alg_3d_summer_2017_no_ind, ...
    gr_alg_3d_summer_2017_no_ind] = data_vectors(mat_summer_2017_norm, ...
    mat_summer_2017_no_ind_3d);
[no_alg_3d_summer_2017_randn_w_ind, bg_alg_3d_summer_2017_randn_w_ind, ...
    gr_alg_3d_summer_2017_randn_w_ind] = data_vectors(mat_summer_2017_norm, ...
    mat_summer_2017_randn_w_ind_3d);
[no_alg_3d_summer_2017_randn_no_ind, bg_alg_3d_summer_2017_randn_no_ind, ...
    gr_alg_3d_summer_2017_randn_no_ind] = data_vectors(mat_summer_2017_norm, ...
    mat_summer_2017_randn_no_ind_3d);

% mendota summer (2015-2017)
[no_alg_3d_mendota_summer_w_ind, bg_alg_3d_mendota_summer_w_ind, ...
    gr_alg_3d_mendota_summer_w_ind] = data_vectors(mat_mendota_summer_norm, ...
    mat_mendota_summer_w_ind_3d);
[no_alg_3d_mendota_summer_no_ind, bg_alg_3d_mendota_summer_no_ind, ...
    gr_alg_3d_mendota_summer_no_ind] = data_vectors(mat_mendota_summer_norm, ...
    mat_mendota_summer_no_ind_3d);
[no_alg_3d_mendota_summer_randn_w_ind, bg_alg_3d_mendota_summer_randn_w_ind, ...
    gr_alg_3d_mendota_summer_randn_w_ind] = data_vectors(mat_mendota_summer_norm, ...
    mat_mendota_summer_randn_w_ind_3d);
[no_alg_3d_mendota_summer_randn_no_ind, bg_alg_3d_mendota_summer_randn_no_ind, ...
    gr_alg_3d_mendota_summer_randn_no_ind] = data_vectors(mat_mendota_summer_norm, ...
    mat_mendota_summer_randn_no_ind_3d);

% monona summer (2015-2017)
[no_alg_3d_monona_summer_w_ind, bg_alg_3d_monona_summer_w_ind, ...
    gr_alg_3d_monona_summer_w_ind] = data_vectors(mat_monona_summer_norm, ...
    mat_monona_summer_w_ind_3d);
[no_alg_3d_monona_summer_no_ind, bg_alg_3d_monona_summer_no_ind, ...
    gr_alg_3d_monona_summer_no_ind] = data_vectors(mat_monona_summer_norm, ...
    mat_monona_summer_no_ind_3d);
[no_alg_3d_monona_summer_randn_w_ind, bg_alg_3d_monona_summer_randn_w_ind, ...
    gr_alg_3d_monona_summer_randn_w_ind] = data_vectors(mat_monona_summer_norm, ...
    mat_monona_summer_randn_w_ind_3d);
[no_alg_3d_monona_summer_randn_no_ind, bg_alg_3d_monona_summer_randn_no_ind, ...
    gr_alg_3d_monona_summer_randn_no_ind] = data_vectors(mat_monona_summer_norm, ...
    mat_monona_summer_randn_no_ind_3d);

% All Data summer (2014-2017)
[no_alg_3d_all_data_summer_w_ind, bg_alg_3d_all_data_summer_w_ind, ...
    gr_alg_3d_all_data_summer_w_ind] = data_vectors(mat_all_data_summer_norm, ...
    mat_all_data_summer_w_ind_3d);
[no_alg_3d_all_data_summer_no_ind, bg_alg_3d_all_data_summer_no_ind, ...
    gr_alg_3d_all_data_summer_no_ind] = data_vectors(mat_all_data_summer_norm, ...
    mat_all_data_summer_no_ind_3d);

% All Data mendota summer (2014-2017)
[no_alg_3d_mendota_all_data_summer_w_ind, bg_alg_3d_mendota_all_data_summer_w_ind, ...
    gr_alg_3d_mendota_all_data_summer_w_ind] = data_vectors(mat_mendota_all_data_summer_norm, ...
    mat_mendota_all_data_summer_w_ind_3d);
[no_alg_3d_mendota_all_data_summer_no_ind, bg_alg_3d_mendota_all_data_summer_no_ind, ...
    gr_alg_3d_mendota_all_data_summer_no_ind] = data_vectors(mat_mendota_all_data_summer_norm, ...
    mat_mendota_all_data_summer_no_ind_3d);

% All Data monona summer (2014-2017)
[no_alg_3d_monona_all_data_summer_w_ind, bg_alg_3d_monona_all_data_summer_w_ind, ...
    gr_alg_3d_monona_all_data_summer_w_ind] = data_vectors(mat_monona_all_data_summer_norm, ...
    mat_monona_all_data_summer_w_ind_3d);
[no_alg_3d_monona_all_data_summer_no_ind, bg_alg_3d_monona_all_data_summer_no_ind, ...
    gr_alg_3d_monona_all_data_summer_no_ind] = data_vectors(mat_monona_all_data_summer_norm, ...
    mat_monona_all_data_summer_no_ind_3d);

%% Plot Summer 2017 Data Points

PCA_3D_algae_plot(no_alg_3d_summer_2017_w_ind, bg_alg_3d_summer_2017_w_ind, ...
    gr_alg_3d_summer_2017_w_ind)
title('Summer 2017 3D, With Indicator')
legend('no algae', 'blue-green algae', 'green algae')

PCA_3D_algae_plot(no_alg_3d_summer_2017_no_ind, bg_alg_3d_summer_2017_no_ind, ...
    gr_alg_3d_summer_2017_no_ind)
title('Summer 2017 3D, No Indicator')
legend('no algae', 'blue-green algae', 'green algae')

PCA_3D_algae_plot(no_alg_3d_summer_2017_randn_w_ind, bg_alg_3d_summer_2017_randn_w_ind, ...
    gr_alg_3d_summer_2017_randn_w_ind)
title('Summer 2017 3D Randn Projection, With Indicator')
legend('no algae', 'blue-green algae', 'green algae')

PCA_3D_algae_plot(no_alg_3d_summer_2017_randn_no_ind, bg_alg_3d_summer_2017_randn_no_ind, ...
    gr_alg_3d_summer_2017_randn_no_ind)
title('Summer 2017 3D Randn Projection, No Indicator')
legend('no algae', 'blue-green algae', 'green algae')

%% Plot Mendota Summer Data Points

PCA_3D_algae_plot(no_alg_3d_mendota_summer_w_ind, bg_alg_3d_mendota_summer_w_ind, ...
    gr_alg_3d_mendota_summer_w_ind)
title('Mendota Summer (June-August) 3D, With Indicator')
legend('no algae', 'blue-green algae', 'green algae')

PCA_3D_algae_plot(no_alg_3d_mendota_summer_no_ind, bg_alg_3d_mendota_summer_no_ind, ...
    gr_alg_3d_mendota_summer_no_ind)
title('Mendota Summer (June-August) 3D, No Indicator')
legend('no algae', 'blue-green algae', 'green algae')

PCA_3D_algae_plot(no_alg_3d_mendota_summer_randn_w_ind, bg_alg_3d_mendota_summer_randn_w_ind, ...
    gr_alg_3d_mendota_summer_randn_w_ind)
title('Mendota Summer (June-August) 3D Randn Projection, With Indicator')
legend('no algae', 'blue-green algae', 'green algae')

PCA_3D_algae_plot(no_alg_3d_mendota_summer_randn_no_ind, bg_alg_3d_mendota_summer_randn_no_ind, ...
    gr_alg_3d_mendota_summer_randn_no_ind)
title('Mendota Summer (June-August) 3D Randn Projection, No Indicator')
legend('no algae', 'blue-green algae', 'green algae')

%% Plot Monona Summer Data Points

PCA_3D_algae_plot(no_alg_3d_monona_summer_w_ind, bg_alg_3d_monona_summer_w_ind, ...
    gr_alg_3d_monona_summer_w_ind)
title('monona Summer (June-August) 3D, With Indicator')
legend('no algae', 'blue-green algae', 'green algae')

PCA_3D_algae_plot(no_alg_3d_monona_summer_no_ind, bg_alg_3d_monona_summer_no_ind, ...
    gr_alg_3d_monona_summer_no_ind)
title('monona Summer (June-August) 3D, No Indicator')
legend('no algae', 'blue-green algae', 'green algae')

PCA_3D_algae_plot(no_alg_3d_monona_summer_randn_w_ind, bg_alg_3d_monona_summer_randn_w_ind, ...
    gr_alg_3d_monona_summer_randn_w_ind)
title('Monona Summer (June-August) 3D Randn Projection, With Indicator')
legend('no algae', 'blue-green algae', 'green algae')

PCA_3D_algae_plot(no_alg_3d_monona_summer_randn_no_ind, bg_alg_3d_monona_summer_randn_no_ind, ...
    gr_alg_3d_monona_summer_randn_no_ind)
title('Monona Summer (June-August) 3D Randn Projection, No Indicator')
legend('no algae', 'blue-green algae', 'green algae')

%% Plot All Data Summer Points

PCA_3D_algae_plot(no_alg_3d_all_data_summer_w_ind, bg_alg_3d_all_data_summer_w_ind, ...
    gr_alg_3d_all_data_summer_w_ind)
title('All Data Summer (June-August) 3D, With Indicator')
legend('no algae', 'blue-green algae', 'green algae')

PCA_3D_algae_plot(no_alg_3d_all_data_summer_no_ind, bg_alg_3d_all_data_summer_no_ind, ...
    gr_alg_3d_all_data_summer_no_ind)
title('All Data Summer (June-August) 3D, No Indicator')
legend('no algae', 'blue-green algae', 'green algae')

%% Plot All Data Mendota Points

PCA_3D_algae_plot(no_alg_3d_mendota_all_data_summer_w_ind, bg_alg_3d_mendota_all_data_summer_w_ind, ...
    gr_alg_3d_mendota_all_data_summer_w_ind)
title('Mendota All Data Summer (June-August) 3D, With Indicator')
legend('no algae', 'blue-green algae', 'green algae')

PCA_3D_algae_plot(no_alg_3d_mendota_all_data_summer_no_ind, bg_alg_3d_mendota_all_data_summer_no_ind, ...
    gr_alg_3d_mendota_all_data_summer_no_ind)
title('Mendota All Data Summer (June-August) 3D, No Indicator')
legend('no algae', 'blue-green algae', 'green algae')

%% Plot All Data Monona Points

PCA_3D_algae_plot(no_alg_3d_monona_all_data_summer_w_ind, bg_alg_3d_monona_all_data_summer_w_ind, ...
    gr_alg_3d_monona_all_data_summer_w_ind)
title('Monona All Data Summer (June-August) 3D, With Indicator')
legend('no algae', 'blue-green algae', 'green algae')

PCA_3D_algae_plot(no_alg_3d_monona_all_data_summer_no_ind, bg_alg_3d_monona_all_data_summer_no_ind, ...
    gr_alg_3d_monona_all_data_summer_no_ind)
title('Monona All Data Summer (June-August) 3D, No Indicator')
legend('no algae', 'blue-green algae', 'green algae')
