#!/bin/bash

python3 Matrix_Build_no_na.py
python3 All_Data_Matrix_Build.py
python3 Location_Matrix_Build_no_na.py
python3 Data_Norm.py
python3 Compute_Eigenvectors.py
python3 eigen_no_algae_indicator.py
python3 Data_Projection.py
python3 PCA.py
python3 Gaussian_Rand_Projection.py

